kolpak/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^kolpak/', include('mainapp.urls')),
    url(r'^admin/', admin.site.urls),
]

mainapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^articles/(?P<article_id>[0-9]+)/$', views.get_article, name="get_article"),
    url(r'^articles/$', views.get_articles, name="get_articles"),
    url(r'^articles/create/$', views.create_article, name="create_article"),
    url(r'^articles/(?P<article_id>[0-9]+)/edit/$', views.edit_article, name="edit_article"),
    url(r'^articles/(?P<article_id>[0-9]+)/comments/create$', views.create_article_comment, name="create_article_comment"),
    url(r'^articles/(?P<article_id>[0-9]+)/upload/', views.upload_article_file, name="upload_article_file"),

    url(r'^persons/(?P<person_id>[0-9]+)/$', views.get_person, name="get_person"),
    url(r'^persons/$', views.get_persons, name="get_persons"),
    url(r'^persons/create/$', views.create_person, name="create_person"),
    url(r'^persons/(?P<person_id>[0-9]+)/edit/$', views.edit_person, name="edit_person"),
    url(r'^persons/(?P<person_id>[0-9]+)/comments/create$', views.create_person_comment, name="create_person_comment"),

    url(r'^tasks/$', views.get_tasks, name='get_tasks'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/results$', views.ResultsView.as_view(), name='results'),
]

mainapp/models.py
from __future__ import unicode_literals

from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    birth_date = models.DateField(null=True)
    description = models.TextField()

    class Meta:
        db_table = 'person'

    def __str__(self):
        return ' '.join([self.name, self.surname])

    def __eq__(self, other):
        return isinstance(other, Person) and other.id == self.id

    def short_name(self):
        return "{0} {1}.".format(self.surname, self.name[0])


class File(models.Model):
    name = models.CharField(max_length=100)
    path = models.CharField(max_length=255)
    creation_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'file'


class Article(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    file = models.ForeignKey(File, on_delete=models.SET_NULL, null=True)
    journal = models.CharField(max_length=255)
    publication_date = models.DateField(null=True
                                        # , input_formats=['%Y', '%d/%m/%Y', '%m/%Y', '%d-%m-%Y', '%m-%Y']
                                        )
    authors = models.ManyToManyField(Person, db_table='author_to_article', related_name='articles')

    class Meta:
        db_table = 'article'


class AuthorToArticle(models.Model):
    author = models.ForeignKey(Person, db_column='author_id')
    article = models.ForeignKey(Article, db_column='article_id')

    class Meta:
        db_table = 'author_to_article'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'comment'
        ordering = ('-date',)

mainapp/forms.py
from django import forms
from django.forms.forms import BaseForm
from models import Article, Person


class AuthorsChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.short_name


class ArticleForm(forms.Form):
    def __init__(self, data=None, name=None, description=None, publication_date=None):
        super(ArticleForm, self).__init__(data)
        self.name = forms.CharField(max_length=255, initial=name)
        self.description = forms.Textarea()
        self.authors = AuthorsChoiceField(queryset=Person.objects.all(), required=False)
        self.publication_date = forms.DateField(initial=publication_date)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Person, Article, File
from django.core.urlresolvers import reverse
from datetime import datetime
import time
from django.conf import settings


def index(request):
    return render(request, 'mainapp/index.html')


def get_person(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    return render(request, 'mainapp/person.html', {'person': person})


def get_persons(request):
    return render(request, 'mainapp/persons.html', {'persons': Person.objects.all()})


def get_article(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    return render(request, 'mainapp/article.html', {'article': article})


def get_articles(request):
    return render(request, 'mainapp/articles.html', {'articles': Article.objects.all()})


def edit_person(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    return render(request, 'mainapp/edit_person.html', {'person': person})


def create_article(request):
    article = Article()
    return create_edit_article(request, article, 'Create article', 'Create', reverse('mainapp:create_article'))


def edit_article(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    return create_edit_article(request, article, 'Edit article', 'Update',
                               reverse('mainapp:edit_article', args=(article.id,)))


def create_edit_article(request, article, title, action, action_url):
    if request.method == 'GET':
        context = {
            'article': article,
            'title': title,
            'action': action,
            'action_url': action_url,
            'all_authors': Person.objects.all(),
        }
        return render(request, 'mainapp/edit_article.html', context)
    else:
        article.name = request.POST['name']
        article.description = request.POST['description']
        article.publication_date = datetime.strptime(request.POST['publication_date'], '%d/%m/%Y')
        if not article.id:
            article.save()
        article.authors = Person.objects.filter(id__in=[int(a) for a in request.POST.getlist('authors')])
        article.save()

        return HttpResponseRedirect(reverse('mainapp:get_article', args=(article.id,)))


def create_article_comment(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    text = request.POST['text']
    article.comment_set.create(text=text)
    return HttpResponseRedirect(reverse('mainapp:get_article', args=(article.id,)))


def create_person_comment(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    text = request.POST['text']
    person.comment_set.create(text=text)
    return HttpResponseRedirect(reverse('mainapp:get_person', args=(person_id,)))


def create_person(request):
    person = Person()
    if request.method == 'GET':
        context = {
            'person': person,
            'title': 'Add person',
            'action': 'Create',
            'action_url': reverse('mainapp:create_person'),
        }
        return render(request, 'mainapp/edit_person.html', context)
    else:
        person.name = request.POST['name']
        person.surname = request.POST['surname']
        person.description = request.POST['description']
        if request.POST['birth_date']:
            person.birth_date = datetime.strptime(request.POST['birth_date'], '%d/%m/%Y')
        person.save()
        return HttpResponseRedirect(reverse('mainapp:create_person'))


def get_tasks(request):
    return HttpResponse('Tasks list stub')


def upload_article_file(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    file_data = request.FILES['file']
    extension = '.' + file_data.name.split('.')[-1]
    filepath = settings.FILE_REPO + str(int(time.mktime(datetime.now().timetuple()))) + extension
    name = file_data.name
    with open(filepath, 'wb+') as destination:
        for chunk in file_data.chunks():
            destination.write(chunk)
        file = File(name=name, path=filepath)
        file.save()
        file.article_set.add(article)

    return HttpResponseRedirect(reverse('mainapp:get_article', args=(article_id,)))

mainapp/templates/mainapp/article.html
{% extends 'mainapp/main_frame.html' %}
{% block title %}{{ article.name }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <button type="button" class="btn btn-default"
                    onclick="location.href = '{% url 'mainapp:edit_article' article.id %}'">Edit</button>
        </div>
        <div class="col-sm-8 text-right">
            Created: {{ article.creation_date|date:"d-M-Y" }}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 text-right">
            Published: {{ article.publication_date|date:"M-Y" }}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 text-center">
            <h4><b>{{ article.name }}</b></h4>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">Authors:
            {% for item in article.authors.all %}
                <button type="button" class="btn btn-info"
                        onclick="location.href = '{% url 'mainapp:get_person' item.id %}'">{{ item.short_name }}</button>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 text-center">Description</div>
    </div>
    <div class="row">
        <div class="col-sm-12">{{ article.description }}</div>
    </div>
    <div class="row">
        <div class="col-sm-12" colspan="2">
            <form action="{% url 'mainapp:upload_article_file' article.id %}" method="post"
                       enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <table><tr>
                    <!--TODO fix file opening-->
                    <td><a href="{{ article.file.path }}">{{ article.file.name }}</a></td>
                    <td><input type="file" name="file" /></td>
                    <td><button type="submit" class="btn btn-default">Upload</button></td>
                </tr></table>
                <!--TODO finish with input file styling-->
                <!--<div class="btn btn-default" onclick="document.getElementById('file').click()">-->
                    <!--<span>Choose file</span>-->
                    <!--<input type="file" id="file" name="file" style="visibility: hidden; width: 0; height:0"/>-->
                <!--</div>-->
                <!--<span class="fileinput-filename"></span><span class="fileinput-new">${article.file.path}</span>-->
            </form>
        </div>
    </div>

    <!-- tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="active">
            <a href="#article_comments" role="tab" data-toggle="tab">Comments</a>
        </li>
        <li><a href="#article_history" role="tab" data-toggle="tab">History</a></li>
    </ul>
    <!-- tabs content -->
    <div class="tab-content createArticle_tabContent">
        <div class="tab-pane fade active in" id="article_comments">
            <div class="row">
                <div class="col-sm-12">
                    {% include 'mainapp/create_comment.html' with action='mainapp:create_article_comment' commented_id=article.id %}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">{% include 'mainapp/comments.html' with commented=article %}</div>
            </div>
        </div>
        <div class="tab-pane fade" id="article_history">
            <!-- TODO fix history -->

            <!--<c:forEach items="${article.history}" var="event" end="${math:min(fn:length(article.history), historyLimit)}">-->
                <!--<div class="row">-->
                    <!--<div class="col-sm-4">${event.action}</div>-->
                    <!--<div class="col-sm-8"><fmt:formatDate value="${event.date}" pattern="dd-MM-yyyy HH:mm" /></div>-->
                <!--</div>-->
            <!--</c:forEach>-->
        </div>
    </div>

</div>
{% endblock %}

mainapp/templates/mainapp/articles.html
{% extends 'mainapp/main_frame.html' %}
{% block title %}All Articles{% endblock %}
{% block content %}
<input type="search" class="table-filter" data-table="order-table" placeholder="Filter">

<table class="table table-hover order-table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Published</th>
        </tr>
    </thead>
    {% for item in articles %}
        <tr onclick="location.href = '{% url 'mainapp:get_article' item.id %}'">
            <td>{{ item.name }}</td>
            <td>
                {% if item.authors.all %}
                    {% with item.authors.all|first as author %}
                        <a href="{% url 'mainapp:get_person' author.id %}">{{ author.short_name}}</a>
                    {% endwith %}
                {% else %}
                    no author
                {% endif %}
            </td>
            <td>{{ item.publication_date|date:"Y" }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

mainapp/templates/mainapp/comments.html
{% for item in commented.comment_set.all %}
    <div class="row">
        <div class="col-sm-8">{{ item.text }}</div>
        <div class="col-sm-4">{{ item.date|date:"d-M-Y H:i" }}</div>
    </div>
{% endfor %}

mainapp/templates/mainapp/create_comment.html
<form action="{% url action commented_id %}" method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <div class="col-sm-6">
            <input type="text" name="text" class="form-control" placeholder="Enter comment" />
        </div>
        <div class="col-sm-6">
            <button type="submit" class="btn btn-default pull-left">Comment</button>
        </div>
    </div>
</form>

mainapp/templates/mainapp/edit_article.html
{% extends 'mainapp/main_frame.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<form action="{{ action_url }}" method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    <div class="form-group">
        <label for="createArticle_name"
               class="control-label col-sm-2">Title:</label>
        <div class="col-sm-10">
            <input name="name" id="createArticle_name"
                   class="form-control" placeholder="Enter title" value="{{ article.name }}">
        </div>
    </div>
    <div class="form-group">
        <label for="createArticle_description"
               class="control-label col-sm-2">Description:</label>
        <div class="col-sm-10">
            <textarea name="description" id="createArticle_description"
                      class="form-control" placeholder="Enter description" >{{ article.description }}</textarea>
        </div>

    </div>
    <!-- TODO make search and tags for selected authors -->
    <div class="form-group">
        <label for="createArticle_authors" class="control-label col-sm-2">Author:</label>
        <div class="col-sm-10">
            <select multiple="multiple" name="authors" class="form-control"
                    id="createArticle_authors">
                {% for item in all_authors %}
                    <option value="{{ item.id }}" {% if item in article.authors.all %}selected{% endif %}>{{ item.short_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="createArticle_publicationDate"
               class="control-label col-sm-2">Published:</label>
        <div class="col-sm-10">
            <input name="publication_date" id="createArticle_publicationDate"
                   class="form-control" placeholder="dd/mm/yyyy" value="{{ article.publication_date|date:"d/m/Y" }}"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">{{ action }}</button>
        </div>
    </div>

</form>
{% endblock %}

mainapp/templates/mainapp/edit_person.html
{% extends 'mainapp/main_frame.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<form action="{{ action_url }}" method="post" role="form" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="createPerson_name"
               class="control-label col-sm-2">Name:</label>
        <div class="col-sm-10">
            <input name="name" id="createPerson_name"
                   class="form-control" placeholder="Enter name" value="{{ person.name }}" />
        </div>
    </div>
    <div class="form-group">
        <label for="createPerson_surname"
               class="control-label col-sm-2">Surname:</label>
        <div class="col-sm-10">
            <input name="surname"  id="createPerson_surname"
                   class="form-control" placeholder="Enter surname" value="{{ person.surname }}" />
        </div>
    </div>
    <div class="form-group">
        <label for="createPerson_description"
               class="control-label col-sm-2">Description:</label>
        <div class="col-sm-10">
            <textarea name="description" id="createPerson_description"
                      class="form-control" placeholder="Enter description" >{{ person.description }}</textarea>
        </div>
    </div>
    <div class="form-group">
        <label for="createPerson_birthDate"
               class="control-label col-sm-2">Birth date:</label>
        <div class="col-sm-10">
            <input name="birth_date" id="createPerson_birthDate"
                   class="form-control" placeholder="dd/mm/yyyy" value="{{ person.birth_date|date:'d/m/Y' }}"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">{{ action }}</button>
        </div>
    </div>

</form>
{% endblock %}

mainapp/templates/mainapp/index.html
<h1>Main page</h1>

mainapp/templates/mainapp/main_frame.html
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>


    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="{% static 'mainapp/style.css' %}" rel="stylesheet">
    <script src="{% static 'mainapp/table_filter.js' %}"></script>

</head>
<body>

{% include 'mainapp/navigation.html' %}
<div class="container-fluid">
    {% block content %}{% endblock %}
</div>


</body>
</html>

mainapp/templates/mainapp/navigation.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">Kolpak</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown"
                   href="{% url 'mainapp:get_articles' %}">
                    Articles
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'mainapp:get_articles' %}">All articles</a></li>
                    <li><a href="{% url 'mainapp:create_article' %}">Add Article</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown"
                   href="{% url 'mainapp:get_persons' %}">
                    Persons
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'mainapp:get_persons' %}">All Persons</a></li>
                    <li><a href="{% url 'mainapp:create_person' %}">Add Person</a></li>
                </ul>
            </li>
            <li class="inactive"><a href="{% url 'mainapp:get_tasks' %}">Tasks</a></li>
        </ul>
    </div>
</nav>

mainapp/templates/mainapp/person.html
{% extends 'mainapp/main_frame.html' %}
{% block title %}{{ person.surname }}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-4">
        <button type="button" class="btn btn-default"
                onclick="location.href = '{% url 'mainapp:edit_person' person.id %}'">Edit</button>
    </div>
    <div class="col-sm-8 text-right">
        {{ person.birth_date|date:"d-M-Y" }}
    </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center">
        <h4><b>{{ person.name }} {{ person.surname }}</b></h4>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center">Description</div>
</div>
<div class="row">
    <div class="col-sm-12">{{ person.description }}</div>
</div>

<!--tabs-->
<ul class="nav nav-tabs" role="tablist">
    <li class="active">
        <a href="#person_comments" role="tab" data-toggle="tab">Comments</a>
    </li>
    <li><a href="#person_history" role="tab" data-toggle="tab">History</a></li>
    <li><a href="#person_articles" role="tab" data-toggle="tab">Articles</a></li>
</ul>

<!--tabs content-->
<div class="tab-content createArticle_tabContent">
    <div class="tab-pane fade active in" id="person_comments">
        <div class="row">
            {% include 'mainapp/create_comment.html' with action='mainapp:create_person_comment' commented_id=person.id %}
        </div>
        <div class="row">
            <div class="col-sm-12">{% include 'mainapp/comments.html' with commented=person %}</div>
        </div>
    </div>
    <div class="tab-pane fade" id="person_history">
    </div>
    <div class="tab-pane fade" id="person_articles">
        <table class="table table-hover">
            {% for item in person.articles.all %}
                <tr onclick="location.href = '{% url 'mainapp:get_article' item.id %}'">
                    <td>{{ item.name }}</td>
                    <td>{{ item.publication_date|date:"M-Y" }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/persons.html
{% extends 'mainapp/main_frame.html' %}
{% block title %}All Persons{% endblock %}

{% block content %}
<input type="search" class="table-filter" data-table="order-table" placeholder="Filter">

<table class="table table-hover order-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Birth date</th>
        </tr>
    </thead>
    {% for item in persons %}
        <tr onclick="location.href = '{% url 'mainapp:get_person' item.id %}'">
            <td>{{ item.name }}</td>
            <td>{{ item.surname }}</td>
            <td>{{ item.birth_date|date:"d-M-Y" }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}